### ISSUE TITLE
Wishlist: permanent resumed state

### ISSUE THREAD

**Issue by legovini** [Eloston/disable-html5-autoplay#2]
A wishlist idea: add an option to stay in a permanent "resumed state", where the videos don't start automatically, but it's possible to start them with their play button, without having to switch from the "suspended state" to the "resumed state".

Also, I'd suggest to exchange the icons for the two states.

Thanks!

**Comment by Eloston** [comment]
I'm actually working on a new version that doesn't require a button. It'll disable autoplay but not break media player controls. Your proposal seems to be asking for this.

I don't really want to swap the icons for the two states because I wanted to follow what a media player does: it shows the icon for the action it will take if one clicks it.
