### ISSUE TITLE
Clarify reason for accessing browsing history

### ISSUE THREAD

**Issue by AlanTheBeast** [Eloston/disable-html5-autoplay#30]
Per the install instructions in Chrome, this plugin "Can read your browsing history."

1.  Why?  All the plugin needs to do to do its job is look for the offending audio/video of the loading page and block it.  It does not need access to browsing history.

2. Is the user's browsing data reported from the plugin to Eloston or to other parties?

Reading browsing history is potentially a privacy violation if the data leaves the user's computer.

If data does leave the computer then it should be declared in the plug-in description.

Further, if there is some functional advantage to reading browsing history, then there should be an option to disable the reporting of such data outside the user's computer.

![screen shot 2015-11-26 at 11 53 59](https://cloud.githubusercontent.com/assets/16036095/11427877/6ed126ee-9434-11e5-8692-c9c972621929.jpg)

**Comment by Eloston** [comment]
There is a brief explanation of all permissions used [on the Wiki here](https://github.com/Eloston/disable-html5-autoplay/wiki/Explanation%20of%20Permissions).

"Read your browsing history" is a misleading description, and it can show up even though I don't have access to your browsing history. I'm guessing this shows up either through the `<all_urls>` or `webNavigation` permission, since both give me indirect access to the current tab's URL. The URL is used only for [Mode Rules](https://github.com/Eloston/disable-html5-autoplay/wiki/Modes%20and%20Mode%20Rules).

**To be explicit: This extension does not have access to your browsing history, nor does it send any data anywhere.** You can confirm this yourself by looking through the source code (it's not that long.)

I will update the Wiki with this information as well. Thanks for bringing this to my attention.

**Comment by AlanTheBeast** [comment]
Thanks for the clarification.  I guess Google need to be clearer or more detailed in their functional impact descriptions.
