### ISSUE TITLE
Not working in Chrome  43.0.2357.134 / linux

### ISSUE THREAD

**Issue by gnarlie** [Eloston/disable-html5-autoplay#36]
Using Chrome 43.0.2357.134 on Linux, extension version  0.6.1. 

The extension never enables and does not work.

When I go to the options page, I'm getting

    Uncaught SyntaxError: Unexpected token [      options.js:24

in the developer tools menu.

**Comment by Eloston** [comment]
[This problem is documented in the Wiki here](https://github.com/Eloston/disable-html5-autoplay/wiki/Support#i-am-running-an-old-version-of-chrome-or-opera-and-i-encountered-a-problem).

You need to add `--args --js-flags="--harmony-computed-property-names"` to your Chrome command-line arguments, go to `chrome://flags/#enable-javascript-harmony` and click enable on `Enable Experimental JavaScript`, or upgrade to at least Chrome 44.
