### ISSUE TITLE
Disable HTML5 Autoplay doesn't work with Chrome v49

### ISSUE THREAD

**Issue by CallPaul** [Eloston/disable-html5-autoplay#44]
Ever since Chrome updated, this program hasn't stopped a single video from autoplaying.  I've tried uninstalling, reinstall, etc., to no avail.  It used to work great, but now it's just taking up space.

**Comment by Eloston** [comment]
Does it stop the videos on [this page](http://shapeshed.com/examples/HTML5-video-element/)? There is a video near the bottom of the page with audio that should autoplay without this extension enabled.

**Comment by chapma26** [comment]
Hi @Eloston,

I was having the same issue as @CallPaul . I checked the page in your link above and it does indeed stop them. However, you can check [here](http://www.marketwatch.com/story/45-of-americans-pay-no-federal-income-tax-2016-02-24) for a page that waits a bit and then loads the video and the plugin doesn't seem to catch it.

**Comment by Eloston** [comment]
Thanks for confirming @chapma26. As long as that page works, and @CallPaul cannot show us a website that works on an older Chrome but not Chrome 49, then this bug is invalid.

@chapma26: I use an ad blocker, and I'm not seeing any videos on that page. Is the video an advertisement? In any case, follow the steps outlined [here](https://github.com/Eloston/disable-html5-autoplay/wiki/Support#media-on-site-x-still-autoplays) and create a new bug report if you have to (do not reply to this one).
