### ISSUE TITLE
UX Improvements

### ISSUE THREAD

**Issue by jens1978** [Eloston/disable-html5-autoplay#69]
May I suggest a simple UI improvement?
My first opinion was, that Autoplay means that videos start immediately, hence, Autoplay. Before checking back with the wiki, I didn’t knew, Nothing, means do nothing. Instead my suggestion is, use a switch made from CSS. No extra Javascript needed.
As far as I see, the button Default Mode has only 2 states. Video Autoplay On or Off.
The select list might not be the best way to present it.

This simple change, will fix the confusion. The enhancement now is; it is easier to differ which state is selected by the user.
![video-autoplay_1_default](https://cloud.githubusercontent.com/assets/2441984/17107099/1ddf9626-528e-11e6-8973-286f47490b16.png)
![video-autoplay_2_on](https://cloud.githubusercontent.com/assets/2441984/17107100/1de5b2d6-528e-11e6-94e3-eee2cbfee112.png)
![video-autoplay_3_off](https://cloud.githubusercontent.com/assets/2441984/17107098/1dde7732-528e-11e6-848a-1902c5c9426d.png)

**Comment by Eloston** [comment]
Actually I already made a fix in the code. I made it say "Disable autoplay" and "Disable nothing" instead of those two. I use a drop down list because in the future I will have a third option for "Disable autoplay and autobuffering" (and "Disable autoplay" will become "Disable autoplay only").

Thanks for the suggestion though.
