### ISSUE TITLE
Autoplay of audio from chat box

### ISSUE THREAD

**Issue by LucasD3** [Eloston/disable-html5-autoplay#8]
At the following URL, which requires logging in with a Google account, a chat window pops up after logging in, and audio starts playing automatically which consists of the computer speaking the text from the chat window:

http://outliner.setpixel.com/

I tried looking at the javascript console and I found something regarding an HTML audio element, so I assume this is an HTML5 issue. I don't know whether this counts technically as an "autoplay" issue.

Operating System: Mac OS 10.10.4
Chrome Version: 44.0.2403.155 (64-bit)
Extension Version: 0.4.2 (updated with Fix #7 )

**Comment by Eloston** [comment]
I tried logging in into that website, and no chat window pops up automatically and tries to speak to me. How did you get it to speak to you?

If my extension's icon is shown in color, then an HTML5 video or audio element is present on the page.

Assuming that there is HTML5 audio present, it's possible that you were clicking or typing within 1.5 before the audio play() function invoked. In this case, then the audio will play.

**Comment by LucasD3** [comment]
Actually it's initially just a minimized chat field at the bottom right of the screen, but upon mouseover it pops into a chat window. 

I believe it is indeed HTML5 audio, although the extension icon remains grey. I looked at the javascript, and it seems to be using the Speech Synthesis API:

http://outliner.setpixel.com/js/speech.js

https://developers.google.com/web/updates/2014/01/Web-apps-that-talk---Introduction-to-the-Speech-Synthesis-API

For me, the audio starts playing without any interaction (no clicking or typing), and it continues playing for several seconds until the entire chat text has been spoken (the chat text is automatically generated).

**Comment by Eloston** [comment]
If my extension says that there's no media on the page, it's almost guarenteed to be correct. I also inspected the page with the Developer console, and couldn't find any HTML5 media elements on the page.

The Speech Synthesis API is an API implemented by the browser, and doesn't use HTML5 audio elements. I wasn't getting any audio because of my custom build of Chromium.

Since this website isn't speaking with HTML5 media, I will close this issue. If you don't want the Speech API to work, you could try using the command line switch `--disable-speech-api` when you start Chrome.
