### ISSUE TITLE
What's up with the master branch?

### ISSUE THREAD

**Issue by liltinkerer** [Eloston/disable-html5-autoplay#92]
What is up with the master branch? Is it behind or what is inside the [background.js](https://github.com/Eloston/disable-html5-autoplay/blob/master/background.js)? Checked source code and was wondering. 0.6-maintenance branch makes more sense and is actually the source that at least Chrome is using.

**Comment by Eloston** [comment]
`master` has been and will always be the newest and latest developments. Right now, it is a very early WIP for 0.7 that hasn't been touched for ages. Then it would become development for 0.8, 0.9, etc. I also just realized I haven't pushed some other small changes I've made that hasn't been touched in ages.

`0.6-maintenance` was created because there were some small fixes that I wanted to make to the 0.6 series, but the codebase was already being rewritten for 0.7 on `master`.
